name: remote

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=version::$(cat .version)"
        id: set_version

      - run: echo "hello from ${{ steps.set_version.outputs.version}}"

      - run: echo "hello from caller"
      - run: |
          echo "GITHUB_WORKFLOW $GITHUB_WORKFLOW"
          echo "GITHUB_EVENT_NAME $GITHUB_EVENT_NAME"
          echo "GITHUB_REF $GITHUB_REF"

      - run: |
          echo "1"
          echo "2"
          echo "3"
