name: two

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:

      - name: Set env

        run: echo "GITHUB_SHA=refs/pull/1/merge" >> $GITHUB_ENV

      - run: echo "two"
